### ISSUE TITLE
update script - Error apply: Zeile 446: [: 9.: Ganzzahliger Ausdruck erwartet.

### ISSUE THREAD

**Issue by spitzlbergerj** [sdetweil/MagicMirror_scripts#81]
Hi,

I have just started the update script and after checking if an npm update is needed I get the following error message:

```
No npm upgrade necessary.

apply: Zeile 446: [: 9.: Ganzzahliger Ausdruck erwartet.
computing size, want /var/swap=1866MByte, checking existing: deleting wrong size
```

This message is then repeated during further program steps

I then tried to stop the update with CRTL-C, but this apparently only led to a subroutine being aborted. The script continued to run. Since then, some modules no longer work.

Starting the script again does not work because the script thinks that the update has already run.

What does the error message mean?
How can I force the update script to run again?

Thanks for your help
Josef Spitzlberger

**Comment by sdetweil** [comment]
can u send me the ~/MagicMirror/installers/upgrade.log 
same userid at gmail

I do not know, never seen that message..

can you show output of 

npm -v

**Comment by spitzlbergerj** [comment]
here it is

Thanks for your help

[upgrade.log](https://github.com/sdetweil/MagicMirror_scripts/files/13844054/upgrade.log)

**Comment by sdetweil** [comment]
yep.. doah..   

can u try upgrade again and change the word 
```
apply 
```
to
``` 
force
```

**Comment by spitzlbergerj** [comment]
The output translated to english ist
```
force: Line 447: V9 8.1: Command not found.
force: Line 448: [: -ge: Single-character (unary) operator expected.
force: Line 699: [: 9th: Integer expression expected.
```

yes, option force done

the output is

```
m/sdetweil/MagicMirror_scripts/master/upgrade-script.sh)" force
update log will be in /home/pi/MagicMirror/installers/upgrade.log
doing test run = false
Node currently installed. Checking version number.
Minimum Node version: v18.18.0
Installed Node version: v18.18.0
Check current Node installation ...
Node currently installed. Checking version number.
Minimum Node version: v18.18.0
Installed Node version: v18.18.0
No Node.js upgrade necessary.
Check current NPM installation ...
NPM currently installed. Checking version number.
Minimum npm version: V9.8.1
Installed npm version: V9.8.1
No npm upgrade necessary.

force: Zeile 447: V9 8.1: Kommando nicht gefunden.
force: Zeile 448: [: -ge: Einstelliger (unärer) Operator erwartet.
saving custom.css
upgrading from version 2.26.0 to 2.26.0
fetching latest revisions
updating MagicMirror runtime, please wait
force: Zeile 699: [: 9.: Ganzzahliger Ausdruck erwartet.
npm WARN config only Use `--omit=dev` to omit dev dependencies from the install.

[ ....... very long time nothing .....]


> magicmirror@2.26.0 postinstall
> npm run install-vendor && npm run install-fonts && echo "MagicMirror² installation finished successfully!
> "


> magicmirror@2.26.0 install-vendor
> echo "Installing vendor files ...
> " && cd vendor && npm install --loglevel=error --no-audit --no-fund --no-update-notifier

Installing vendor files ...


up to date in 4s

> magicmirror@2.26.0 install-fonts
> echo "Installing fonts ...
> " && cd fonts && npm install --loglevel=error --no-audit --no-fund --no-update-notifier

Installing fonts ...


up to date in 3s
MagicMirror² installation finished successfully!


> magicmirror@2.26.0 prepare
> [ -f node_modules/.bin/husky ] && husky install || echo no husky installed.

no husky installed.

added 343 packages in 3m

98 packages are looking for funding
  run `npm fund` for details

Checking for modules with removed libraries

updating dependencies for active modules with package.json files


        processing for module MMM-Remote-Control please wait

        ----------------------------------
npm WARN config only Use `--omit=dev` to omit dev dependencies from the install.

...
```

**Comment by sdetweil** [comment]
glad its working..

**Comment by spitzlbergerj** [comment]
Thank you very much

**Comment by sdetweil** [comment]
if you want to try it again... won't hurt anything.. see if I fixed the error.. 
with force

**Comment by spitzlbergerj** [comment]
Good morning,
I have just tried it again. The first two error messages are now gone. But I still get the message for line 737 
`force: Line 737: [: 9.: Integer expression expected.`

Thank you for your time and effort.
It's simply amazing how much you care about every message here. THANK YOU

**Comment by sdetweil** [comment]
thanks.. fixed that one too
